name: theia extension
on: [push]

jobs:
  build-and-test:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node: ["14.x", "16.x"]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: yarn
        run: |
          yarn install
          yarn run prepare
          yarn run rebuild:browser
          yarn test
