name: theia extension
on: [push]

env:
  NODE_VERSION: "14.x"

jobs:
  build-and-test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: yarn install
        run: |
          yarn install
          yarn run prepare
          yarn run rebuild:browser
